import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/providers";
import Header from "./components/header";
import "react-icons/fc";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="az" className="light text-black  bg-white">
      <body className={inter.className}>
        <Header />
        <Providers>
          <main className=" min-h-screen flex flex-col items-center">
            {children}
          </main>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
